package paramgen

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"regexp"
	"strconv"
	"strings"

	"github.com/wzhqwq/vrcft-go/internal/specparser"
)

var goIdentifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func Generate(doc *specparser.Document, packageName string, source []byte) ([]byte, error) {
	if doc == nil {
		return nil, fmt.Errorf("nil document")
	}
	if !goIdentifier.MatchString(packageName) {
		return nil, fmt.Errorf("invalid package name %q", packageName)
	}

	all := doc.All()
	for _, item := range all {
		if !goIdentifier.MatchString(item.Spec.Name) {
			return nil, fmt.Errorf("parameter name %q is not a Go identifier", item.Spec.Name)
		}
	}

	hash := sha256.Sum256(source)
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by cmd/paramgen; DO NOT EDIT.")
	fmt.Fprintf(&out, "// Source SHA-256: %x\n\n", hash)
	fmt.Fprintf(&out, "package %s\n\n", packageName)

	fmt.Fprintln(&out, "const (")
	for i, item := range all {
		if i == 0 {
			fmt.Fprintf(&out, "\tParameter%s ParameterID = iota\n", item.Spec.Name)
		} else {
			fmt.Fprintf(&out, "\tParameter%s\n", item.Spec.Name)
		}
	}
	fmt.Fprintln(&out, ")")
	fmt.Fprintf(&out, "\nconst ParameterCount ParameterID = %d\n\n", len(all))

	fmt.Fprintln(&out, "var Definitions = [ParameterCount]ParameterDefinition{")
	for _, classified := range all {
		item := classified.Spec
		fmt.Fprintf(&out, "\tParameter%s: {\n", item.Name)
		fmt.Fprintf(&out, "\t\tID: Parameter%s,\n", item.Name)
		fmt.Fprintf(&out, "\t\tName: %s,\n", strconv.Quote(item.Name))
		fmt.Fprintf(&out, "\t\tOSCName: %s,\n", strconv.Quote(item.OSCName))
		fmt.Fprintf(&out, "\t\tGroup: %s,\n", strconv.Quote(item.Group))
		fmt.Fprintf(&out, "\t\tKind: %s,\n", kindConstant(classified.Kind))
		fmt.Fprintf(&out, "\t\tValueType: %s,\n", valueTypeConstant(item.ValueType))
		fmt.Fprintf(&out, "\t\tEncodings: %s,\n", encodingExpression(item.SupportedEncodings))
		if item.Range != nil {
			fmt.Fprintf(&out, "\t\tRange: ValueRange{Min: %s, Max: %s},\n", number(item.Range.Min), number(item.Range.Max))
			fmt.Fprintln(&out, "\t\tHasRange: true,")
		}
		if item.Unit != "" {
			fmt.Fprintf(&out, "\t\tUnit: %s,\n", strconv.Quote(item.Unit))
		}

		switch item.ValueType {
		case "float":
			semantics, err := item.FloatSemantics()
			if err != nil {
				return nil, fmt.Errorf("parameter %q: %w", item.OSCName, err)
			}
			fmt.Fprintln(&out, "\t\tSemantics: []SemanticRange{")
			for _, semantic := range semantics {
				fmt.Fprintf(&out, "\t\t\t{Min: %s, Max: %s, Meaning: %s},\n",
					number(semantic.Range[0]), number(semantic.Range[1]), strconv.Quote(semantic.Meaning))
			}
			fmt.Fprintln(&out, "\t\t},")
		case "bool":
			semantics, err := item.ParseBoolSemantics()
			if err != nil {
				return nil, fmt.Errorf("parameter %q: %w", item.OSCName, err)
			}
			fmt.Fprintf(&out, "\t\tBool: BoolSemantics{True: %s, False: %s},\n",
				strconv.Quote(semantics.True), strconv.Quote(semantics.False))
		}
		if item.SendPolicy != "" {
			fmt.Fprintf(&out, "\t\tSendPolicy: %s,\n", strconv.Quote(item.SendPolicy))
		}
		fmt.Fprintln(&out, "\t},")
	}
	fmt.Fprintln(&out, "}")

	fmt.Fprintln(&out, "\nvar ParameterByOSCName = map[string]ParameterID{")
	for _, classified := range all {
		item := classified.Spec
		fmt.Fprintf(&out, "\t%s: Parameter%s,\n", strconv.Quote(item.OSCName), item.Name)
	}
	fmt.Fprintln(&out, "}")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, out.String())
	}
	return formatted, nil
}

func kindConstant(kind string) string {
	switch kind {
	case "detailed":
		return "KindDetailed"
	case "simplified":
		return "KindSimplified"
	case "tracking_active":
		return "KindTrackingActive"
	default:
		panic("unexpected parameter kind: " + kind)
	}
}

func valueTypeConstant(valueType string) string {
	switch valueType {
	case "float":
		return "ValueFloat"
	case "bool":
		return "ValueBool"
	default:
		panic("unexpected value type: " + valueType)
	}
}

func encodingExpression(encodings []string) string {
	parts := make([]string, 0, len(encodings))
	for _, encoding := range encodings {
		switch encoding {
		case "float":
			parts = append(parts, "EncodingFloat")
		case "binary":
			parts = append(parts, "EncodingBinary")
		case "bool":
			parts = append(parts, "EncodingBool")
		default:
			panic("unexpected encoding: " + encoding)
		}
	}
	if len(parts) == 0 {
		return "0"
	}
	return strings.Join(parts, " | ")
}

func number(value float32) string {
	return strconv.FormatFloat(float64(value), 'f', -1, 32)
}
