import {localTime} from '../lib/presentation/time.js'

export const copy = {
  navigation: {
    overview: '概览',
    plugins: '插件',
    settings: '设置',
    diagnostics: '诊断',
  },
  actions: {
    save: '保存',
    cancel: '取消',
    retry: '重试',
    copy: '复制',
  },
  settings: {
    savedRestart: '已保存，将在重启后生效',
  },
  state: {
    loading: '正在加载', ready: '已就绪', stale: '数据可能已过期', problem: '启动失败',
    normal: '正常', attention: '需要处理', absent: '尚无数据',
    active: '活跃', inactive: '未活跃', enabled: '已启用', disabled: '已停用', unknown: '未知状态',
    phase: {
      created: '尚未启动', starting: '正在启动', running: '运行中', degraded: '运行受限', diagnostic: '诊断模式',
      failed: '启动失败', stopping: '正在停止', stopped: '已停止', closing: '正在关闭', closed: '已关闭', unsupported: '平台不受支持',
    },
    plugin: {
      discovered: '已发现', disabled: '已停用', starting: '正在启动', handshaking: '正在握手', running: '运行中',
      stopped: '已停止', stopping: '正在停止', crashed: '已崩溃', error: '运行错误',
      failed: '启动失败', unresponsive: '无响应', incompatible: '不兼容', backoff: '等待重试', restarting: '正在重启',
    },
    plan: {ready: '已就绪', empty: '尚无计划', pending: '正在生成', error: '计划错误', failed: '计划失败'},
    osc: {
      not_running: {label: 'OSC 未运行', discovery: '未启动'},
      discovering: {label: '正在发现 OSC 输出', discovery: '正在发现'},
      discovered: {label: '已发现 OSC 输出', discovery: '自动发现'},
      manual: {label: '正在使用手动 OSC 输出', discovery: '手动目标'},
      error: {label: 'OSC 输出错误', discovery: '发现出错'},
    },
  },
  pluginCard: {
    enable: (name: string) => `启用 ${name}`,
    capabilities: (name: string) => `${name} 能力`,
    pending: '正在更新此插件。', lifecycle: '生命周期', frameRate: '帧率', restarts: '重启次数',
    error: '插件运行提示', important: '需要关注的插件',
  },
  text: {
    runStatus: '运行状态',
    readRunStatus: '正在读取运行状态',
    noRunStatus: '暂无可显示的运行状态',
    noRunDescription: '应用完成初始化后，当前 Avatar 和 OSC 输出会显示在这里。',
    phase: '应用阶段',
    oscOutput: 'OSC 输出',
    oscAbsent: '尚未提供 OSC 输出状态。',
    avatarPlan: 'Avatar 计划',
    planStatus: '计划状态',
    source: '来源',
    generation: '迭代',
    configState: '配置状态',
    unconfigured: '尚未配置',
    noPlan: '尚未生成可用计划。',
    missingAvatarConfig: '未找到当前 Avatar 的配置',
    missingAvatarConfigDescription: '请在设置中选择 Fallback Avatar 配置文件，以便为未识别的 Avatar 绑定参数。',
    pluginOverview: '插件概览',
    readPluginOverview: '正在读取插件概览',
    noPluginOverview: '暂无可显示的插件概览',
    noPluginOverviewDescription: '插件列表可用后会在这里显示汇总信息。',
    noPlugins: '未发现插件',
    noPluginsDescription: '发现或安装插件后，会在这里显示其状态。',
    pluginOperations: '插件操作问题',
    pluginsDescription: '搜索、查看并立即管理本地插件。',
    pluginList: '插件列表',
    readPluginList: '正在读取插件列表',
    noPluginData: '暂无可显示的插件',
    pluginReconnect: '应用恢复连接后会显示插件列表。',
    pluginFilters: '插件筛选',
    pluginSearch: '搜索插件',
    pluginSearchPlaceholder: '按名称或 ID 搜索',
    pluginStateFilter: '插件状态筛选',
    filterAll: '全部',
    filterProblems: '只看问题',
    noMatchingPlugins: '没有符合条件的插件',
    adjustFilters: '请调整搜索词或状态筛选条件。',
    pagination: '插件分页',
    previousPage: '上一页',
    nextPage: '下一页',
    general: '常规',
    processing: '处理',
    automatic: '自动',
    manual: '手动',
    settingsDescription: '这些设置将在下次重启后应用。',
    readSettings: '正在读取设置',
    settingsUnavailable: '设置不可用',
    settingsUnavailableDetail: '设置数据暂时不可用，请稍后重试。',
    settingsConflict: '设置冲突',
    settingsChanged: '设置已在其他位置更新',
    reloadWarning: '重新加载会放弃当前未保存的更改。',
    reloadSettings: '重新加载设置',
    generalSettings: '常规设置',
    generalDescription: 'Avatar 配置与本地插件开发目录。',
    avatarRoot: 'Avatar OSC 根目录',
    avatarFallback: 'Fallback Avatar 配置',
    processingProblems: '处理配置问题',
    defaultChannel: '默认通道处理',
    defaultChannelDescription: '校准、调节、滤波和丢失数据策略。',
    processingProfiles: '通道处理',
    processingProfilesDescription: '默认处理适用于所有通道；自定义处理只替换指定通道的参数。',
    processingProfile: '处理配置',
    defaultProcessing: '默认处理',
    addCustomProcessing: '添加自定义处理',
    removeCustomProcessing: '删除自定义处理',
    overrideChannelName: '覆盖通道名称',
    overrideChannelNameDescription: '填写需要单独处理的通道名称。',
    activeStale: '活跃通道过期时长（毫秒）',
    overrides: '通道覆盖',
    overridesDescription: '为指定通道替换默认处理参数。',
    mutualExclusion: '互斥组',
    mutualDescription: '同组通道不会同时输出。',
    oscTarget: 'OSC 目标',
    oscTargetDescription: '选择自动发现或手动目标。',
    targetMode: '目标模式',
    preferredService: '首选发现服务',
    preferredDescription: '自动模式下优先使用此发现服务。',
    preferredDisabled: '仅自动模式可编辑首选发现服务。',
    manualHost: '手动主机',
    manualHostDescription: '手动模式下使用 IP 地址作为 OSC 目标。',
    manualDisabled: '仅手动模式可编辑主机和端口。',
    manualPort: '手动端口',
    manualPortDescription: '端口必须在 1 到 65535 之间。',
    dirty: '有未保存的更改',
    reloadConfirmDescription: '确认后将使用最新保存的设置。',
    confirmReload: '确认重新加载',
    revision: '版本号',
    noRevision: '尚无',
    updatedAt: '更新时间',
    notUpdated: '尚未更新',
    notProvided: '未提供',
    noTarget: '未设置输出目标',
    diagnosticsDescription: '三个独立模块的当前可见状态。',
    moduleStatus: '模块状态',
    copyDiagnostics: '复制诊断信息',
    runtimeStatus: 'Runtime 状态',
    readRuntime: '正在读取 Runtime 状态',
    noRuntime: 'Runtime 尚无数据',
    noRuntimeDescription: 'Runtime 启动或恢复连接后，会显示应用和输出状态。',
    application: '应用',
    lifecycle: '生命周期',
    platformSupport: '平台支持',
    supported: '受支持',
    unsupported: '不受支持',
    config: '配置',
    planNeedsAttention: 'Avatar 计划需要处理',
    noAvatarPlan: '尚未生成 Avatar 计划',
    noAvatarPlanDescription: '收到 Avatar 变更后，会显示当前计划状态。',
    mode: '模式',
    target: '目标',
    error: '错误',
    oscError: '有 OSC 错误',
    none: '无',
    noOsc: '尚未提供 OSC 状态',
    noOscDescription: 'OSC 启动后会显示当前输出目标。',
    unsupportedTitle: '当前平台暂不受支持',
    retainedRuntime: 'Runtime 仍会保留可用的状态信息。',
    pluginControlFailed: '插件控制失败',
    pluginsStartupFailed: 'Plugins 启动失败',
    pluginsStartupFailedDescription: '请检查插件服务后重试；其他模块仍可继续使用。',
    pluginsDiagnosticsDescription: '发现或安装插件后，会在这里显示插件诊断。',
    settingsNoData: 'Settings 尚无数据',
    settingsNoDataDescription: '设置模块恢复连接后，会显示其修订和状态。',
    unsavedDescription: '你有尚未保存的更改。',
    unsaved: '未保存的更改',
    discard: '放弃更改',
    saveChanges: '保存更改',
    savingChanges: '正在保存更改',
    currentAvatar: '当前 Avatar',
    copyAvatar: '复制 Avatar ID',
    readAvatar: '正在读取 Avatar 信息',
    name: '名称',
    discovery: '发现方式',
    outputTarget: '输出目标',
    devRoots: '插件开发目录',
    devRootsDescription: '仅添加用于开发和测试本地插件的绝对目录。',
    addDevRoot: '添加开发目录',
    overrideEditorDescription: '仅为指定通道替换默认处理参数。',
    processingParameters: '处理参数',
    addOverride: '添加通道覆盖',
    mutualEditorDescription: '同一组中的通道不会同时输出。',
    addGroup: '添加互斥组',
    noFilter: '不启用平滑',
    calibration: '输入校准',
    enableCalibration: '启用输入校准',
    enableCalibrationDescription: '根据下面的基准和范围修正追踪器输入。',
    neutral: '静止基准值',
    neutralDescription: '没有动作时，追踪器通常输出的数值。',
    min: '输入下限',
    minDescription: '追踪器产生最小动作时的数值。',
    max: '输入上限',
    maxDescription: '追踪器产生最大动作时的数值。',
    calibrationGain: '校准强度',
    calibrationGainDescription: '放大或缩小校准后的动作幅度。',
    invertCalibration: '反转输入方向',
    invertCalibrationDescription: '交换动作的正负方向。',
    tuning: '响应调节',
    deadzone: '忽略微小输入',
    deadzoneDescription: '低于此幅度的变化将视为没有动作。',
    tuningGain: '响应强度',
    tuningGainDescription: '整体放大或缩小输出幅度。',
    exponent: '响应曲线',
    exponentDescription: '调整小动作与大动作之间的响应比例。',
    enableClamp: '限制输出范围',
    enableClampDescription: '将输出约束在下面的上下限之间。',
    clampMin: '输出下限',
    clampMax: '输出上限',
    filter: '平滑处理',
    filterMode: '平滑方式',
    filterModeDescription: '选择如何减少输入抖动。',
    emaAlpha: 'EMA 响应速度',
    emaAlphaDescription: '数值越大越灵敏，越小越平滑。',
    minCutoff: '基础响应速度',
    minCutoffDescription: 'One Euro 在动作较慢时的响应速度。',
    filterBeta: '动态响应系数',
    filterBetaDescription: '提高快速动作时的跟随速度。',
    derivativeCutoff: '速度变化平滑度',
    derivativeCutoffDescription: '控制 One Euro 对动作速度变化的平滑程度。',
    dropout: '信号丢失处理',
    holdDuration: '保持最后值时长（毫秒）',
    holdDurationDescription: '信号中断后，继续保持最后一个有效值的时间。',
    decayDuration: '回到默认值时长（毫秒）',
    decayDurationDescription: '保持结束后，逐渐回到默认值所需的时间。',
    staleAfter: '判定信号过期时间（毫秒）',
    staleAfterDescription: '超过此时间未收到更新，就将信号视为中断。',
    rootRequired: 'Avatar OSC 根目录不能为空。',
    devRootRequired: '插件开发目录不能为空。',
    finiteProcessing: '处理参数必须是有限数字。',
    finiteActiveStale: '活跃通道过期时长必须是有限数字。',
    invalidOverrides: '覆盖名称必须非空且唯一，处理参数必须是有限数字。',
    groupNameRequired: '互斥组中的通道名称不能为空。',
    invalidMode: 'OSC 目标模式必须是自动或手动。',
    invalidPreferred: '手动模式不能设置首选发现服务。',
    hostRequired: '手动模式需要目标主机。',
    invalidPort: '端口必须是 1 到 65535 之间的整数。',
    checkInput: '请检查输入',
    leaveTrigger: '放弃未保存的更改',
    leaveTitle: '放弃未保存的更改？',
    leaveDescription: '离开设置不会保存或清除当前草稿。',
  },
  format: {
    pluginSummary: (total: number, active: number, problem: number) => `${total} 个插件 · ${active} 个活跃 · ${problem} 个问题`,
    pluginCounts: (total: number, enabled: number, active: number, problem: number) => `共 ${total} 个插件 · 已启用 ${enabled} · 活跃 ${active} · 问题 ${problem}`,
    page: (page: number, total: number) => `第 ${page} 页，共 ${total} 页`,
    staleSettings: (time: string | null) => `显示上次可用设置 · ${localTime(time)}`,
    revision: (revision: number) => `修订 ${revision}`,
    diagnostic: (code: string) => `问题代码：${code}`,
    devRoot: (index: number) => `开发目录 ${index}`,
    removeDevRoot: (index: number) => `删除开发目录 ${index}`,
    override: (index: number) => `通道覆盖 ${index}`,
    overrideName: (index: number) => `覆盖通道名称 ${index}`,
    removeOverride: (index: number) => `删除通道覆盖 ${index}`,
    customProcessing: (name: string) => `自定义：${name}`,
    unnamedCustomProcessing: (index: number) => `自定义处理 ${index + 1}`,
    group: (index: number) => `互斥组 ${index}`,
    groupMembers: (index: number) => `互斥组 ${index} 成员`,
    removeGroup: (index: number) => `删除互斥组 ${index}`,
  },
  problem: {
    validation: {
      title: '输入内容需要调整',
      defaultDetail: '请检查输入后重试。',
    },
    conflict: {
      title: '数据已在其他位置更新',
      defaultDetail: '当前数据已更新，请重新加载后再试。',
      detailWithRevision: (revision: number) => `当前版本已更新到修订 ${revision}，请重新加载后再试。`,
    },
    notFound: {
      title: '未找到所需内容',
      defaultDetail: '未找到所需内容。',
    },
    unavailable: {
      title: '当前功能暂不可用',
      defaultDetail: '请稍后重试，或检查应用是否仍在运行。',
    },
    unsupportedPlatform: {
      title: '当前平台暂不受支持',
      defaultDetail: '此功能当前仅支持受支持的平台环境。',
    },
    timeout: {
      title: '操作响应超时',
      defaultDetail: '请求处理时间过长，请重试。',
    },
    internal: {
      title: '应用发生内部错误',
      defaultDetail: '应用返回了受限错误信息，请复制诊断信息后重试。',
    },
    unknown: {
      title: '发生未知错误',
      defaultDetail: '应用返回了未识别的问题类型。',
    },
  },
} as const

export type Copy = typeof copy
