// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig(arg1) {
  return window['go']['main']['PluginsAPI']['GetConfig'](arg1);
}

export function List() {
  return window['go']['main']['PluginsAPI']['List']();
}

export function SetEnabled(arg1, arg2) {
  return window['go']['main']['PluginsAPI']['SetEnabled'](arg1, arg2);
}

export function UpdateConfig(arg1, arg2, arg3) {
  return window['go']['main']['PluginsAPI']['UpdateConfig'](arg1, arg2, arg3);
}
