// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig(arg1:string):Promise<main.PluginConfigResponse>;

export function List():Promise<main.PluginListResponse>;

export function SetEnabled(arg1:string,arg2:boolean):Promise<main.PluginMutationResponse>;

export function UpdateConfig(arg1:string,arg2:number,arg3:string):Promise<main.PluginMutationResponse>;
