// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiagnostics() {
  return window['go']['main']['RuntimeAPI']['GetDiagnostics']();
}

export function GetStatus() {
  return window['go']['main']['RuntimeAPI']['GetStatus']();
}

export function ReportFrontendError(arg1, arg2) {
  return window['go']['main']['RuntimeAPI']['ReportFrontendError'](arg1, arg2);
}
