// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetDiagnostics():Promise<main.DiagnosticsResponse>;

export function GetStatus():Promise<main.RuntimeResponse>;

export function ReportFrontendError(arg1:string,arg2:string):Promise<void>;
