// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Get() {
  return window['go']['main']['SettingsAPI']['Get']();
}

export function Save(arg1, arg2) {
  return window['go']['main']['SettingsAPI']['Save'](arg1, arg2);
}

export function Validate(arg1) {
  return window['go']['main']['SettingsAPI']['Validate'](arg1);
}
