// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {userconfig} from '../models';

export function Get():Promise<main.SettingsResponse>;

export function Save(arg1:number,arg2:userconfig.Candidate):Promise<main.SettingsSaveResponse>;

export function Validate(arg1:userconfig.Candidate):Promise<main.SettingsValidationResponse>;
